#!/usr/bin/env bash
# Capture `toilet 0.3-1` byte fixtures for the rusty-figlet strict-compat
# corpus (E012 T052). Invoked by `.github/workflows/capture-strict-compat-corpus.yml`.
#
# Output layout (per docs/strict-compat-corpus-capture.md §4):
#
#   tests/fixtures/toilet-corpus/
#     ascii/<id>.bytes           # captured stdout bytes
#     ascii/<id>.meta.txt        # input + filter + version + timestamp + kernel
#     utf8-multicolumn/<id>.bytes
#     utf8-multicolumn/<id>.meta.txt
#     edge-width/<id>.bytes
#     edge-width/<id>.meta.txt
#     manifest.yaml              # YAML index of all captures
#
# Asserts:
# - `toilet --version` reports the expected `toilet 0.3-1` line.
# - `uname -a` is recorded into the manifest.
# - At least 22 fixtures are captured across the three category folders
#   (≥10 ascii, ≥6 utf8-multicolumn, ≥6 edge-width per plan §Strict-compat
#   corpus categorization).
#
# Safety:
# - All inputs are explicit literals enumerated below — NEVER `eval` or
#   read from environment / argv / file. Adversarial inputs can only be
#   introduced via a PR review.
# - `set -euo pipefail` + `IFS=$'\n\t'` for defensive shell.
# - Per-fixture binary capture uses `>` redirect (NOT `cat`-piped through
#   any UTF-8 normaliser).

set -euo pipefail
IFS=$'\n\t'

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CORPUS_DIR="$REPO_ROOT/tests/fixtures/toilet-corpus"
MANIFEST="$CORPUS_DIR/manifest.yaml"

mkdir -p "$CORPUS_DIR/ascii" "$CORPUS_DIR/utf8-multicolumn" "$CORPUS_DIR/edge-width"

# Version assertion — fail the workflow if toilet is not installed or the
# version line does not start with the documented major.minor prefix.
TOILET_VERSION="$(toilet --version 2>&1 | head -n1)"
case "$TOILET_VERSION" in
    *"toilet "0.3*) ;;
    *)
        echo "FATAL: expected 'toilet 0.3.*' line, got: $TOILET_VERSION" >&2
        exit 2
        ;;
esac

HOST_KERNEL="$(uname -a)"
APT_POLICY="$(apt-cache policy toilet | grep -E '^\s*Installed:' || echo 'Installed: unknown')"
CAPTURED_AT="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

# Start manifest file (overwrite — fresh capture per run).
{
    echo "# rusty-figlet strict-compat corpus manifest (T052)."
    echo "# Generated by scripts/capture-toilet-corpus.sh — do not edit by hand."
    echo "captured_at: \"$CAPTURED_AT\""
    echo "toilet_version: \"$TOILET_VERSION\""
    echo "host_kernel: \"$HOST_KERNEL\""
    echo "apt_policy: \"$APT_POLICY\""
    echo "fixtures:"
} > "$MANIFEST"

# capture_one <category> <id> <filter-chain> <input>
#
# Captures `toilet -F <filter-chain> <input>` stdout bytes into
# tests/fixtures/toilet-corpus/<category>/<id>.bytes plus a sibling
# .meta.txt and appends a manifest entry. SHA-256 of the bytes is included
# in the manifest for tamper-evidence.
capture_one() {
    local category="$1" id="$2" chain="$3" input="$4"
    local out_dir="$CORPUS_DIR/$category"
    local bytes_path="$out_dir/$id.bytes"
    local meta_path="$out_dir/$id.meta.txt"

    # Run toilet — capture stdout bytes raw, no pipe normalization.
    if [ "$chain" = "" ]; then
        toilet "$input" > "$bytes_path"
    else
        toilet -F "$chain" "$input" > "$bytes_path"
    fi

    # Determinism check: run twice and assert byte-identical output.
    local tmp_second
    tmp_second="$(mktemp)"
    if [ "$chain" = "" ]; then
        toilet "$input" > "$tmp_second"
    else
        toilet -F "$chain" "$input" > "$tmp_second"
    fi
    if ! cmp -s "$bytes_path" "$tmp_second"; then
        echo "FATAL: non-deterministic capture for $category/$id" >&2
        rm -f "$tmp_second"
        exit 3
    fi
    rm -f "$tmp_second"

    local sha
    sha="$(sha256sum "$bytes_path" | awk '{print $1}')"
    local bytes_size
    bytes_size="$(wc -c < "$bytes_path")"

    # Pathological-size guard.
    if [ "$bytes_size" -gt 65536 ]; then
        echo "FATAL: fixture $category/$id exceeds 64 KiB ($bytes_size bytes)" >&2
        exit 4
    fi

    {
        echo "id: $id"
        echo "category: $category"
        echo "input: \"$input\""
        echo "filter_chain: \"$chain\""
        echo "command: \"toilet -F $chain $input\""
        echo "captured_at: $CAPTURED_AT"
        echo "toilet_version: \"$TOILET_VERSION\""
        echo "host_kernel: \"$HOST_KERNEL\""
        echo "bytes_path: \"$category/$id.bytes\""
        echo "bytes_sha256: \"$sha\""
        echo "bytes_size: $bytes_size"
        echo "review_status: \"pending-reviewer\""
    } > "$meta_path"

    {
        echo "  - id: $category/$id"
        echo "    category: $category"
        echo "    input: \"$input\""
        echo "    filter_chain: \"$chain\""
        echo "    command: \"toilet -F $chain $input\""
        echo "    bytes_path: \"$category/$id.bytes\""
        echo "    bytes_sha256: \"$sha\""
        echo "    bytes_size: $bytes_size"
        echo "    review_status: \"pending-reviewer\""
    } >> "$MANIFEST"
}

# ----- ASCII corpus (>= 10 fixtures per plan §Strict-compat) ---------------
capture_one ascii nothing_hello       nothing  "hello"
capture_one ascii nothing_hi          nothing  "hi"
capture_one ascii nothing_abc         nothing  "abc"
capture_one ascii crop_hello          crop     "hello"
capture_one ascii crop_hi             crop     "hi"
capture_one ascii gay_hi              gay      "hi"
capture_one ascii metal_hi            metal    "hi"
capture_one ascii border_hi           border   "hi"
capture_one ascii flip_hi             flip     "hi"
capture_one ascii flop_hi             flop     "hi"
capture_one ascii rotate180_hi        rotate180 "hi"
capture_one ascii chain_crop_border   crop:border "hi"

# ----- UTF-8 multicolumn corpus (>= 6 fixtures) -----------------------------
capture_one utf8-multicolumn nothing_cjk       nothing  "あ"
capture_one utf8-multicolumn nothing_emoji     nothing  "🦀"
capture_one utf8-multicolumn nothing_combining nothing  "é"
capture_one utf8-multicolumn crop_cjk          crop     "あ"
capture_one utf8-multicolumn gay_emoji         gay      "🦀"
capture_one utf8-multicolumn rotate_combining  rotate180 "é"

# ----- Edge-width corpus (>= 6 fixtures) ------------------------------------
capture_one edge-width nothing_empty       nothing  ""
capture_one edge-width nothing_single_char nothing  "a"
capture_one edge-width nothing_max_width   nothing  "the quick brown fox jumps over the lazy dog"
capture_one edge-width long_chain          crop:border:flip:flop:rotate180 "hi"
capture_one edge-width nothing_long_word   nothing  "supercalifragilisticexpialidocious"
capture_one edge-width gay_long            gay      "the quick brown"

# Final manifest tail.
echo "fixture_count: $(grep -c '^  - id:' "$MANIFEST" || echo 0)" >> "$MANIFEST"

echo "OK: captured $(grep -c '^  - id:' "$MANIFEST") fixtures into $CORPUS_DIR"
