#!/usr/bin/env python3
"""Generate syntactically-valid placeholder TLF font files for v0.3.0.

Mirrors the v0.1.0 FLF placeholder approach per AD-006:
- height=1, max_length=8, hardblank=`$`, endmark=`@`
- 95 ASCII glyphs (codepoints 32..=126), each on a single line ending in `@@`
  (doubled endmark since height==1 → only row IS final row)
- comment_lines describes what each font is a placeholder for

Output files:
- assets/fonts/mono9.tlf
- assets/fonts/future.tlf
- assets/fonts/pagga.tlf

NOTE: This script is used ONCE at generation time. The generated .tlf files
are committed to the repo. Re-running this script overwrites them.
"""

import sys
from pathlib import Path

FONTS = [
    ("mono9", "monospace 9-row toilet font (placeholder for v0.3.0)"),
    ("future", "futuristic block style toilet font (placeholder for v0.3.0)"),
    ("pagga", "outlined block style toilet font (placeholder for v0.3.0)"),
]


def comment_block(name: str, desc: str) -> str:
    return "\n".join([
        f"{name}.tlf rusty-figlet v0.3.0 placeholder",
        f"[PLACEHOLDER] {desc}",
        "",
        "This file is a syntactically-valid `tlf2a` placeholder generated by",
        "tools/gen-placeholder-tlf.py during E012 Phase 3 (T013). It exercises",
        "the full TLF parse path (parser -> render -> output) with real code,",
        "only the glyph ART is placeholder. Per AD-006, we ship placeholders",
        "for v0.3.0 because the upstream toilet `.tlf` files cannot be copied",
        "verbatim under clean-room policy.",
        "",
        "Each ASCII codepoint 32..=126 renders as the literal codepoint",
        "character on a single line (height=1). Endmarks use `@` (final row",
        "doubled).",
    ])


def make_tlf(name: str, desc: str) -> str:
    comments = comment_block(name, desc)
    comment_lines = len(comments.split("\n"))
    out = f"tlf2a$ 1 1 8 0 {comment_lines}\n"
    out += comments + "\n"
    for cp in range(32, 127):
        ch = chr(cp)
        # height==1 means the single row is the LAST row → doubled endmark.
        out += f"{ch}@@\n"
    return out


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: gen-placeholder-tlf.py <assets/fonts dir>", file=sys.stderr)
        return 2
    out_dir = Path(sys.argv[1])
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, desc in FONTS:
        content = make_tlf(name, desc)
        target = out_dir / f"{name}.tlf"
        target.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {target} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
